### ISSUE TITLE
Error parsing config.json file - Unexpected end of JSON input

### ISSUE THREAD

**Issue by SlowestTimelord** [DIG-Network/dig-propagation-server#87]
Copying issue from https://github.com/DIG-Network/chia-dig-node/issues/22

> Hi,
> 
> I'm encountering an error when starting the DIG Propagation Server. Below are the details of the error message:
> 
> bash:
> 2024-10-01 20:51:13 propagation-server-1 | Error: Error parsing your configuration file: [/.dig/config.json]: Unexpected end of JSON input
> at File.loadSync (/app/node_modules/nconf/lib/nconf/stores/file.js:170:11)
> at Provider.add (/app/node_modules/nconf/lib/nconf/provider.js:136:23)
> at Provider.file (/app/node_modules/nconf/lib/nconf/provider.js:63:15)
> at NconfManager.initializeConfig (/app/node_modules/@dignetwork/dig-sdk/dist/utils/NconfManager.js:28:25)
> Node.js v20.8.0
> 
> It seems like the config.json file is malformed, leading to a parsing error with the Unexpected end of JSON input message.
> 
> Steps to reproduce the issue:
> Start the DIG Propagation server with the current configuration.
> The error occurs when loading the /.dig/config.json file.
> Expected behavior:
> The server should start normally with the configuration file loaded correctly.
> 
> Actual behavior:
> The server crashes with a parsing error in the config.json file, indicating the file is incomplete or incorrectly formatted.
> 
> Additional information:
> Node.js version: v20.8.0
> File in question: /.dig/config.json
> If you need further details or the current configuration file, I can provide it. Please let me know if any corrections to the JSON syntax are needed or if there is an example of a properly formatted configuration file available.
> 
> Thank you for your help!

**Comment by Sunkiller-qc** [comment]
The fille is here but empty .

**Comment by thesemaphoreslim** [comment]
I'm having this issue as well (screenshot provided).  Created a PR that should resolve it https://github.com/DIG-Network/dig-chia-sdk/pull/155
![image](https://github.com/user-attachments/assets/e5c09363-e3f8-4eeb-aaec-82067490af65)
